name: Build APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Sync Submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: "14742923"
        packages: "platforms;android-37.0 build-tools;37.0.0 platform-tools"

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=0 \
          --install "ndk;29.0.14206865"

        echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV

        sed -i '10i\        \            ndkVersion = "29.0.14206865"' app/build.gradle.kts

    - name: Restore cached libhevtun
      id: cache-libhevtun-restore
      uses: actions/cache/restore@v4
      with:
        path: libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('compile-hevtun.sh') }}

    - name: Build libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      run: |
        set -e

        test -d hev-socks5-tunnel
        test -f hev-socks5-tunnel/Android.mk
        test -f hev-socks5-tunnel/build.mk

        test -f hev-socks5-tunnel/third-part/yaml/Android.mk
        test -f hev-socks5-tunnel/third-part/lwip/Android.mk
        test -f hev-socks5-tunnel/third-part/hev-task-system/Android.mk

        chmod +x compile-hevtun.sh
        ./compile-hevtun.sh

    - name: Save libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('compile-hevtun.sh') }}

    - name: Copy libhevtun
      run: |
        if [ -d libs ]; then
          cp -r libs app/
        fi

    - name: Fetch AndroidLibXrayLite tag
      run: |
        echo "CURRENT_TAG=v26.7.31" >> $GITHUB_ENV

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1.13
      with:
        repository: 2dust/AndroidLibXrayLite
        tag: ${{ env.CURRENT_TAG }}
        fileName: libv2ray.aar
        out-file-path: app